Announcement Sprint #0
CSSIT22/studentlife pull request #12
Opened 2022-11-06 11:51 UTC by nichakontae

### Frontend Part: 
we have total 7 pages -> announcement, create, detail, history, approval, approvalDetail, recyclebin 

**what we have done:**
- completely _UI_ on every pages
- on _announcement_ page, user can pin or unpin (if user pin, it will show on the top)
- on _history_ page, user can edit and delete post (change status of post)
- on _recyclebin_ page, user can recover post (change status of post)
- on _create_ page, can send data that user fill form except _add more language data_, add more language user can add more language

**what we have not done**
- on _detail_ page, doesn't apply information follow the post that user click
- on _approvalDetail_ page, doesn't apply information follow the post that user click
- from second point, it cause to can not do change status post on approval page (waiting -> approve or disapprove)
- _PostOnTop_ component can not expand yet
- on _create_ page, add more language part it cannot cancel more language that user added

2022-11-07 04:19 UTC, ThisTine requested changes
อันนี้เช็คให้เค้านิดนึงนะ

2022-11-07 04:19 UTC, ThisTine commented on frontend/src/components/annoucement/ApporveOrDisapprove.tsx
> +    setAllPost: React.Dispatch<React.SetStateAction<Array<any>>>
อันนี้มี type อื่นนอกจาก any ไหมฮะ หรือมี plan จะเปลี่ยนมั้ย ? ;-;

2022-11-07 04:19 UTC, ThisTine commented on frontend/src/components/annoucement/HeaderPage.tsx
> +            return <Link to={"/announcement/create"} key="1"><Icon fontSize={"2rem"}/></Link>
ทำไมอันนี้มันแปลก ๆ

2022-11-07 04:36 UTC, nichakontae commented on frontend/src/components/annoucement/HeaderPage.tsx
> +            return <Link to={"/announcement/create"} key="1"><Icon fontSize={"2rem"}/></Link>
header ของทุกหน้าจะไม่มี icon เลยอ่ะ ยกเว้นแค่หน้า create ที่เป็นของ creator user เราเลยทำอันแบบนี้ไว้อ่ะ เราไม่แน่ใจว่ามันมีวิธีทำแบบอื่นมั้ย ;-;

2022-11-07 04:37 UTC, nichakontae commented on frontend/src/components/annoucement/ApporveOrDisapprove.tsx
> +    setAllPost: React.Dispatch<React.SetStateAction<Array<any>>>
ใน allPost array นี้อ่ะ ข้อมูลในนี้มีหลาย type มาก ทั้ง string,number,date เราเลยไม่แน่ใจว่าถ้ามันมีหลายๆ type ใน array เดียว จะต้องใส่ type ว่าอะไรอ่ะ เลยใส่ any ไปเลย ;-;

2022-11-07 05:41 UTC, ThisTine commented on frontend/src/components/annoucement/ApporveOrDisapprove.tsx
> +    setAllPost: React.Dispatch<React.SetStateAction<Array<any>>>
อ่า ม่ายเป็นไร ๆ ถ้า type มัน stable กว่านี้ค่อยใส่ก็ได้ฮะ

2022-11-07 07:09 UTC, nichakontae commented on frontend/src/components/annoucement/ApporveOrDisapprove.tsx
> +    setAllPost: React.Dispatch<React.SetStateAction<Array<any>>>
โอเคคับๆ

2022-11-07 07:36 UTC, nichakontae commented on frontend/src/components/annoucement/HeaderPage.tsx
> +            return <Link to={"/announcement/create"} key="1"><Icon fontSize={"2rem"}/></Link>
เราแก้แล้วนะๆ ลองเข้าไปเช็คดูอีกที

2022-11-08 02:53 UTC, ThisTine approved these changes
🤌🤌

2022-11-08 02:53 UTC, ThisTine commented on frontend/src/components/annoucement/HeaderPage.tsx
> +            return <Link to={"/announcement/create"} key="1"><Icon fontSize={"2rem"}/></Link>
ไม่ ๆ แต่ tag มันแปลก

<Link to={"/announcement/create"} key="1"><Icon fontSize={"2rem"}/>
อันนี้มันปิด tag แล้ว
</Link>
ละอันนี้ปิด tag อีกทีอ่ะ

2022-11-08 02:53 UTC, merged